//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

namespace eWamLauncher
{
   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
   public partial class WideIndex
   {

      private Package[] packagesField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Package", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public Package[] packages
      {
         get
         {
            return this.packagesField;
         }
         set
         {
            this.packagesField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class Package
   {

      private PackageComponent[] componentsField;

      private string typeField;

      private string idField;

      private string nameField;

      private string versionField;

      private string descriptionField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Component", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public PackageComponent[] Components
      {
         get
         {
            return this.componentsField;
         }
         set
         {
            this.componentsField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Type
      {
         get
         {
            return this.typeField;
         }
         set
         {
            this.typeField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Id
      {
         get
         {
            return this.idField;
         }
         set
         {
            this.idField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Name
      {
         get
         {
            return this.nameField;
         }
         set
         {
            this.nameField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Version
      {
         get
         {
            return this.versionField;
         }
         set
         {
            this.versionField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Description
      {
         get
         {
            return this.descriptionField;
         }
         set
         {
            this.descriptionField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class PackageComponent
   {

      private ComponentFile[] filesField;

      private string nameField;

      private string compressionField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("File", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
      public ComponentFile[] Files
      {
         get
         {
            return this.filesField;
         }
         set
         {
            this.filesField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Name
      {
         get
         {
            return this.nameField;
         }
         set
         {
            this.nameField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Compression
      {
         get
         {
            return this.compressionField;
         }
         set
         {
            this.compressionField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
   public partial class ComponentFile
   {

      private string pathField;

      private string plateformField;

      private string versionField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Path
      {
         get
         {
            return this.pathField;
         }
         set
         {
            this.pathField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Plateform
      {
         get
         {
            return this.plateformField;
         }
         set
         {
            this.plateformField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Version
      {
         get
         {
            return this.versionField;
         }
         set
         {
            this.versionField = value;
         }
      }

   }
}